### ISSUE TITLE
How to use a file larger than 4m for prediction

### ISSUE THREAD

**Issue by XGL96** [wuhuikai/PointCloudSuperResolution#2]
Thank you for your code. I ran your test_data successfully. 
But when I want to try my own data, I encounter some error about ResourceExhaustedError. I think it's not because of the format of my data file, since I copied your 5000 rows of data 22 times (11000 lines in total) and it faced the same error. The details were as follows:
```
root@0459537d64b5:/pcsr/code# cd /pcsr/code && python3 main_gan.py --dataset ../data/test_data/our_collected_data/more --log_dir ../model/model_res_mesh_pool_gan_ft
0459537d64b5
Namespace(batch_size=1, dataset='../data/test_data/our_collected_data/more', gan=False, gpu='0', lambd=5000, learning_rate=0.001, log_dir='../model/model_res_mesh_pool_gan_ft', max_epoch=80, model='model_res_mesh_pool', model_path=None, num_point=1024, phase='test', up_ratio=4)
 [*] Reading checkpoint from ../model/model_res_mesh_pool_gan_ft/model-40
../model/model_res_mesh_pool_gan_ft/model-40
2020-12-14 05:47:42.335234: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-12-14 05:47:42.435461: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:895] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-12-14 05:47:42.436126: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
name: TITAN RTX major: 7 minor: 5 memoryClockRate(GHz): 1.77
pciBusID: 0000:21:00.0
totalMemory: 23.65GiB freeMemory: 21.56GiB
2020-12-14 05:47:42.436143: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: TITAN RTX, pci bus id: 0000:21:00.0, compute capability: 7.5)
2020-12-14 05:49:41.154113: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 23.65G (25393561600 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
../data/test_data/our_collected_data/more/camel.xyz (1, 110000, 3)
2020-12-14 05:49:52.054207: W tensorflow/core/common_runtime/bfc_allocator.cc:273] Allocator (GPU_0_bfc) ran out of memory trying to allocate 135.23GiB.  Current allocation summary follows.
2020-12-14 05:49:52.054286: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (256): 	Total Chunks: 1, Chunks in use: 1. 256B allocated for chunks. 256B in use in bin. 4B client-requested in use in bin.
2020-12-14 05:49:52.054296: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (512): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-12-14 05:49:52.054315: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (1024): 	Total Chunks: 2, Chunks in use: 2. 2.8KiB allocated for chunks. 2.8KiB in use in bin. 2.5KiB client-requested in use in bin.
2020-12-14 05:49:52.054329: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (2048): 	Total Chunks: 4, Chunks in use: 4. 12.0KiB allocated for chunks. 12.0KiB in use in bin. 12.0KiB client-requested in use in bin.
2020-12-14 05:49:52.054353: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (4096): 	Total Chunks: 1, Chunks in use: 0. 4.2KiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-12-14 05:49:52.054367: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (8192): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-12-14 05:49:52.054376: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (16384): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-12-14 05:49:52.054417: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (32768): 	Total Chunks: 1, Chunks in use: 0. 46.0KiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-12-14 05:49:52.054431: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (65536): 	Total Chunks: 51, Chunks in use: 50. 3.19MiB allocated for chunks. 3.12MiB in use in bin. 3.12MiB client-requested in use in bin.
2020-12-14 05:49:52.054445: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (131072): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-12-14 05:49:52.054455: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (262144): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-12-14 05:49:52.054464: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (524288): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-12-14 05:49:52.054474: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (1048576): 	Total Chunks: 1, Chunks in use: 1. 1.26MiB allocated for chunks. 1.26MiB in use in bin. 1.26MiB client-requested in use in bin.
2020-12-14 05:49:52.054485: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (2097152): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-12-14 05:49:52.054496: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (4194304): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-12-14 05:49:52.054506: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (8388608): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-12-14 05:49:52.054517: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (16777216): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-12-14 05:49:52.054529: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (33554432): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-12-14 05:49:52.054539: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (67108864): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-12-14 05:49:52.054550: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (134217728): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-12-14 05:49:52.054562: I tensorflow/core/common_runtime/bfc_allocator.cc:628] Bin (268435456): 	Total Chunks: 1, Chunks in use: 0. 21.28GiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2020-12-14 05:49:52.054586: I tensorflow/core/common_runtime/bfc_allocator.cc:644] Bin for 135.23GiB was 256.00MiB, Chunk State: 
2020-12-14 05:49:52.054601: I tensorflow/core/common_runtime/bfc_allocator.cc:650]   Size: 21.28GiB | Requested Size: 0B | in_use: 0, prev:   Size: 1.26MiB | Requested Size: 1.26MiB | in_use: 1
2020-12-14 05:49:52.054615: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394000000 of size 1280
2020-12-14 05:49:52.054622: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394000500 of size 65536
2020-12-14 05:49:52.054628: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394010500 of size 65536
2020-12-14 05:49:52.054635: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394020500 of size 65536
2020-12-14 05:49:52.054651: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394030500 of size 65536
2020-12-14 05:49:52.054658: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394040500 of size 65536
2020-12-14 05:49:52.054668: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394050500 of size 65536
2020-12-14 05:49:52.054676: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394060500 of size 256
2020-12-14 05:49:52.054692: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394061700 of size 1536
2020-12-14 05:49:52.054699: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394061d00 of size 3072
2020-12-14 05:49:52.054707: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394062900 of size 3072
2020-12-14 05:49:52.054716: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394063500 of size 3072
2020-12-14 05:49:52.054726: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394064100 of size 3072
2020-12-14 05:49:52.054738: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394070500 of size 65536
2020-12-14 05:49:52.054747: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394080500 of size 65536
2020-12-14 05:49:52.054759: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394090500 of size 65536
2020-12-14 05:49:52.054766: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa3940a0500 of size 65536
2020-12-14 05:49:52.054774: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa3940b0500 of size 65536
2020-12-14 05:49:52.054782: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa3940c0500 of size 65536
2020-12-14 05:49:52.054790: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa3940d0500 of size 65536
2020-12-14 05:49:52.054800: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa3940e0500 of size 65536
2020-12-14 05:49:52.054808: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa3940f0500 of size 65536
2020-12-14 05:49:52.054816: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394100500 of size 65536
2020-12-14 05:49:52.054824: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394110500 of size 65536
2020-12-14 05:49:52.054832: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394120500 of size 65536
2020-12-14 05:49:52.054844: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394130500 of size 65536
2020-12-14 05:49:52.054851: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394140500 of size 65536
2020-12-14 05:49:52.054858: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394150500 of size 65536
2020-12-14 05:49:52.054865: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394160500 of size 65536
2020-12-14 05:49:52.054875: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394170500 of size 65536
2020-12-14 05:49:52.054883: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394180500 of size 65536
2020-12-14 05:49:52.054891: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394190500 of size 65536
2020-12-14 05:49:52.054899: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa3941a0500 of size 65536
2020-12-14 05:49:52.054908: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa3941b0500 of size 65536
2020-12-14 05:49:52.054916: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa3941c0500 of size 65536
2020-12-14 05:49:52.054926: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa3941d0500 of size 65536
2020-12-14 05:49:52.054939: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa3941e0500 of size 65536
2020-12-14 05:49:52.054947: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa3941f0500 of size 65536
2020-12-14 05:49:52.054955: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394200500 of size 65536
2020-12-14 05:49:52.054962: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394210500 of size 65536
2020-12-14 05:49:52.054970: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394220500 of size 65536
2020-12-14 05:49:52.054977: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394230500 of size 65536
2020-12-14 05:49:52.054989: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394240500 of size 65536
2020-12-14 05:49:52.054997: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394250500 of size 65536
2020-12-14 05:49:52.055007: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394260500 of size 65536
2020-12-14 05:49:52.055016: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394270500 of size 65536
2020-12-14 05:49:52.055024: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394280500 of size 65536
2020-12-14 05:49:52.055033: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394290500 of size 65536
2020-12-14 05:49:52.055041: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa3942a0500 of size 65536
2020-12-14 05:49:52.055048: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa3942b0500 of size 65536
2020-12-14 05:49:52.055055: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa3942c0500 of size 65536
2020-12-14 05:49:52.055062: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa3942d0500 of size 65536
2020-12-14 05:49:52.055070: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa3942e0500 of size 65536
2020-12-14 05:49:52.055079: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa3942f0500 of size 65536
2020-12-14 05:49:52.055088: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394310500 of size 65536
2020-12-14 05:49:52.055096: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394320500 of size 65536
2020-12-14 05:49:52.055104: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394330500 of size 65536
2020-12-14 05:49:52.055112: I tensorflow/core/common_runtime/bfc_allocator.cc:662] Chunk at 0x7fa394340500 of size 1320192
2020-12-14 05:49:52.055120: I tensorflow/core/common_runtime/bfc_allocator.cc:671] Free at 0x7fa394060600 of size 4352
2020-12-14 05:49:52.055129: I tensorflow/core/common_runtime/bfc_allocator.cc:671] Free at 0x7fa394064d00 of size 47104
2020-12-14 05:49:52.055137: I tensorflow/core/common_runtime/bfc_allocator.cc:671] Free at 0x7fa394300500 of size 65536
2020-12-14 05:49:52.055145: I tensorflow/core/common_runtime/bfc_allocator.cc:671] Free at 0x7fa394482a00 of size 22849476096
2020-12-14 05:49:52.055152: I tensorflow/core/common_runtime/bfc_allocator.cc:677]      Summary of in-use Chunks by size: 
2020-12-14 05:49:52.055161: I tensorflow/core/common_runtime/bfc_allocator.cc:680] 1 Chunks of size 256 totalling 256B
2020-12-14 05:49:52.055170: I tensorflow/core/common_runtime/bfc_allocator.cc:680] 1 Chunks of size 1280 totalling 1.2KiB
2020-12-14 05:49:52.055178: I tensorflow/core/common_runtime/bfc_allocator.cc:680] 1 Chunks of size 1536 totalling 1.5KiB
2020-12-14 05:49:52.055188: I tensorflow/core/common_runtime/bfc_allocator.cc:680] 4 Chunks of size 3072 totalling 12.0KiB
2020-12-14 05:49:52.055197: I tensorflow/core/common_runtime/bfc_allocator.cc:680] 50 Chunks of size 65536 totalling 3.12MiB
2020-12-14 05:49:52.055206: I tensorflow/core/common_runtime/bfc_allocator.cc:680] 1 Chunks of size 1320192 totalling 1.26MiB
2020-12-14 05:49:52.055214: I tensorflow/core/common_runtime/bfc_allocator.cc:684] Sum Total of in-use chunks: 4.40MiB
2020-12-14 05:49:52.055225: I tensorflow/core/common_runtime/bfc_allocator.cc:686] Stats: 
Limit:                 25393561600
InUse:                     4612352
MaxInUse:                  4612352
NumAllocs:                     113
MaxAllocSize:              1320192

2020-12-14 05:49:52.055240: W tensorflow/core/common_runtime/bfc_allocator.cc:277] *___________________________________________________________________________________________________
2020-12-14 05:49:52.055262: W tensorflow/core/framework/op_kernel.cc:1198] Resource exhausted: OOM when allocating tensor with shape[1,110000,110000,3] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1,110000,110000,3] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: generator/module_0/sub = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](generator/ExpandDims, generator/module_0/ExpandDims_1)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_gan.py", line 282, in <module>
    prediction_whole_model()
  File "main_gan.py", line 260, in prediction_whole_model
    pred_pl = sess.run(pred, feed_dict={pointclouds_ipt: input})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1,110000,110000,3] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: generator/module_0/sub = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](generator/ExpandDims, generator/module_0/ExpandDims_1)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


Caused by op 'generator/module_0/sub', defined at:
  File "main_gan.py", line 282, in <module>
    prediction_whole_model()
  File "main_gan.py", line 242, in prediction_whole_model
    use_normal=use_normal, use_bn=False, use_ibn=False, bn_decay=0.95, up_ratio=UP_RATIO)
  File "/pcsr/code/model_res_mesh_pool.py", line 25, in get_gen_model
    points = pointcnn(xyz, 8, 128, 3, is_training, 'module_0', bn_decay=bn_decay, use_bn=use_bn, use_ibn=use_ibn)
  File "/pcsr/code/res_gcn_module.py", line 53, in pointcnn
    _, grouped_points, _ = group(xyz, None, k)
  File "/pcsr/code/res_gcn_module.py", line 28, in group
    _, idx = knn_point(k*dilation+1, xyz, xyz)
  File "/pcsr/code/tf_ops/grouping/tf_grouping.py", line 57, in knn_point
    dist = tf.reduce_sum((xyz1 - xyz2) ** 2, -1)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 907, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 4856, in _sub
    "Sub", x=x, y=y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1,110000,110000,3] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: generator/module_0/sub = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](generator/ExpandDims, generator/module_0/ExpandDims_1)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
```
It seems that the reason was about the MaxInUse of gpu. I tried to set *gpu_options.per_process_gpu_memory_fraction = 1*, but it still didn't work.
My environment was based on docker from **tensorflow/tensorflow:1.5.1-devel-gpu-py3**. And the test data is in attached camel.zip. I will be grateful if you can solve my issue.

[camel.zip](https://github.com/wuhuikai/PointCloudSuperResolution/files/5686797/camel.zip)

**Comment by wuhuikai** [comment]
One possible solution is splitting the entire mesh into several parts.

**Comment by XGL96** [comment]
But 4612352 is really too small relative to my gpu memory size 25393561600. Did you make any restrictions in your code, or moving data to somewhere like the first level cache?

**Comment by wuhuikai** [comment]
4612352  is the input size. The network will allocate a lot of GPU memory for running.

**Comment by XGL96** [comment]
Actually the memory for running was still not big relative to 25393561600. Do you remember how to cancel the size limitation?

**Comment by wuhuikai** [comment]
![image](https://user-images.githubusercontent.com/6862805/102184341-42dd4980-3eea-11eb-8eb8-6eb30154293e.png)
I'm confused. I have already allow tf to use full memory ......

**Comment by XGL96** [comment]
That was also the point I felt confused ... But I'm sure that I checked nvidia-smi.

**Comment by wuhuikai** [comment]
Can you try a smaller file and show me the screenshot of nvidia-smi?

**Comment by XGL96** [comment]
Sure.
![image](https://user-images.githubusercontent.com/25998168/102315902-e93f5280-3faf-11eb-992d-8d11fa0f1a5f.png)

**Comment by wuhuikai** [comment]
I think that knn  caused this problem. When do knn, a 11000 x 11000 matrix will be generated, which consumes a large part of GPU memory. There's no direct way to replace this function. Maybe try to use some numpy functions to replace this tf operator.

**Comment by XGL96** [comment]
I agree. In fact I've been watching the GPU resources and it's been taking up a few G's and then suddenly crashed. It's possible that, as you say, the consumption suddenly increased when calculating KNN because of the error message "shape[1,110000,110000,3]".

Thank you for your patience.
